//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilce()
        {
            this.Table_IsletmeSahibi = new HashSet<Table_IsletmeSahibi>();
        }
    
        public int id { get; set; }
        public Nullable<int> il_id { get; set; }
        public string ad { get; set; }
    
        public virtual il il { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_IsletmeSahibi> Table_IsletmeSahibi { get; set; }
    }
}
