//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_IsletmeSahibi
    {
        public int Sq_id { get; set; }
        public string Restorant_Adi { get; set; }
        public string Restorant_Sahibi { get; set; }
        public string Restorant_SahibiTel { get; set; }
        public string SubeSorumlusu { get; set; }
        public string SubeSorumlusu_Tel { get; set; }
        public string Restorant_Email { get; set; }
        public string VergiNo { get; set; }
        public string TCNo { get; set; }
        public string Adres { get; set; }
        public string Restorant_Tel { get; set; }
        public Nullable<int> il_id { get; set; }
        public Nullable<int> ilce_id { get; set; }
        public Nullable<int> Rol_id { get; set; }
        public string Sifre { get; set; }
    
        public virtual il il { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual Table_Roller Table_Roller { get; set; }
    }
}
